import { test, expect } from '@playwright/test';
test.setTimeout(1200000);
import { commonSteps } from '../pages/commonSteps';
import { playerAction } from '../pages/playerAction';

test('UH_9459_HALO | Events & Offers | Offer Mgmt/Check-in Flow - Capacity No | ITEMS: No | BACKUP: Max', async ({ page }) => {
    const common = new commonSteps(page)
    const pa = new playerAction(page)

   
  await common.goToHALOWebApplication()
  await common.loginAndSubmit("TU_LAB_HALO_NIN_ADM","Password01@$") 

  await pa.clickOnConfiguration()
  await pa.clickOnEventsAndOffers()
  await pa.clickOnManageEventsAndOffers()
  await pa.clickOnAddNewEventAndOffers()
  await pa.ValidateAddNewEventAndOffersPage()
  await pa.SelectfillOutNewEventFields4("UH_9459_UAT")
  await pa.clickSaveAndNextStep()
  await pa.SelectAFile()
  await pa.clickSaveAndNextStep()
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName1","PC","Skip","500","500")
  await pa.clickOnPrize1()
  await pa.addNewItem("3")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName2","PC","Skip","500","500")
  await pa.clickOnPrize2()
  await pa.addNewItem("3")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName3","PC","Skip","500","500")
  await pa.clickOnPrize3()
  await pa.addNewItem("3")
  await pa.clickSaveAndNextStep()
  await pa.EnterAttendanceCapacity("50")
  await pa.clickSaveAndNextStep()
  await pa.config2()
  await pa.clickSaveAndNextStep()
  await pa.clickSaveAndNextStep()
  await pa.clickSaveAndNextStep()
  await pa.clickOnSubmitForReviewButtonAndVerifyOfferIsSubmittedSuccessfully()
  await pa.validateActiveViewAndApprovedStateSelectedByDefault()
  await pa.selectViewFromEventsAndOfferViewDropdown('All Views')
  await pa.selectStateFromEventsAndOfferStateDropdown('Pending Review')
  await pa.enterOfferName("UH_9459")
  await pa.clickOnSearchForEventsAndOffers()
  await pa.selectThreeDotsAfterCreatorColoumn()
  await pa.clickOnView()
  await pa.validateSummaryPageDisplayed()
  await pa.clickOnApprovedOfferTab()
  await pa.validateOfferApprovedSuccessPopUp()
  await pa.clickOnCloseOfferSuccessPopup1()
  await pa.clickOnEmployeeDashboard()
  await pa.clickOnPlayerFunction()
  await pa.playerFunctionsEventCheckin()
  await pa.searchEventInCheckin('UH_9459')
  await pa.selectEventInCheckin('UH_9459')
  await pa.enterPatronInEventCheckinAndSearch('660302931')  
  await pa.clickOnCheckInButtonInEventCheckIn()
  await pa.validateCheckInSuccessfulPopupAndClose()
  await pa.clickPaceReportButton()
  await pa.validatePaceReportPopupIsOpen()
  await pa.closePaceReportPopup()
  await pa.clickOnEmployeeDashboard()
  await pa.enterPlayerID('660302931')
  await pa.clickOnSearchForPlayer()
  await pa.clickOnClose()
  //await pa.clickOnCloseConsentPopUp()
  await pa.validatePlayerDashboardDisplayed()
  await pa.clickOnPlayerFunction()
  await pa.clickOnPlayerTransactionLog()
  await pa.clickOnLeftArrow()
  await pa.validateEventDetailsInPlayerTransaction()
  await pa.clickOnclosePlayerTransactionWindow()
  await pa.clickOnPlayerReservation()
  await pa.enterPlayerReservationName('UH_9459')
  await pa.clickOnPlayerReservationSearch()
  await pa.clickOnPlayerDetailsLink()
  //await pa.validateEventDetailsPageWithSuccessfullCheckin()
  await page.waitForTimeout(4000);
  await common.logout();
  
    });
