import { test, expect } from '@playwright/test';
test.setTimeout(500000);
import { commonSteps } from '../pages/commonSteps';
import { playerAction } from '../pages/playerAction';

test('UH_9464_HALO | Comments | Settle/Void Comments', async ({ page }) => {
  const common = new commonSteps(page)
  const pa = new playerAction(page)

  await common.goToHALOWebApplication()
  await common.loginAndSubmit("TU_LAB_HALO_NIN_ADM","Password01@$")

  //Scenario1
  await pa.enterPlayerID('807879582')
  await pa.clickOnSearchForPlayer()
  await pa.validatePlayerDashboardDisplayed()
  await pa.clickOnPlayerFunction()
  await pa.clickOnViewComment()
  await pa.validateViewCommentPopUp()
  await pa.clickOnAddCommentTab()
  await pa.selectPriorityAddComment('4-Lower')
  await pa.selectLimitToDepartment('IT')
  await pa.enterText('UH_9464')
  await pa.clickOnSaveViewComment()
  await pa.validateCommentAddedSuccessfullyPopup()
  await pa.clickOnOkMessagePopup()
  await pa.selectComment()
  await pa.validateReplyEditDeletSettleVoidButtonsDisplayed()
  await pa.selectSettleVoidButton()
  await pa.validateDialogBoxWithSettleVoidCommentDisplayed()
  await pa.clickOnCancelSettleVoidCommentBox()
  await pa.selectComment1()
  await pa.selectSettleVoidButton()
  await pa.enterComment('Testing Settle/Void')
  await pa.clickOnSubmit()
  await pa.validateConfirmationMessage()
  await pa.clickOnCancelConfirmationMessagePopUp()
  await pa.clickOnCancelSettleVoidCommentBox()
  await pa.selectComment1()
  await pa.selectSettleVoidButton()
  await pa.enterComment('Testing Settle/Void')
  await pa.clickOnSubmit()
  await pa.validateConfirmationMessage()
  await pa.clickOnConfirm1()
  await pa.validateAuthorizationBox()
  await pa.enterPassword('Password01@$')
  await pa.selectAuthorizationReason('User Error')
  await pa.enterAuthorizationComment('Testing')
  await pa.clickOnAutSubmit()
  await pa.validateMessageCommentSettledSuccessfully()
  await pa.clickOnOk_1()
  await pa.clickOnViewSettledVoidedButton()
  await pa.clickOnCloseComment()
  await common.logout();

  //Scenario2
  await common.goToHALOWebApplication()
  await common.loginAndSubmit("TU_LAB_HALO_NIN_ADM","Password01@$")

  await pa.enterPlayerID('807879582')
  await pa.clickOnSearchForPlayer()
  await pa.validatePlayerDashboardDisplayed()
  await pa.clickOnPlayerFunction()
  await pa.clickOnViewComment()
  await pa.validateViewCommentPopUp()
  await pa.selectComment()
  await pa.validateReplyEditDeletSettleVoidButtonsDisplayed()
  await pa.selectSettleVoidButton()
  await pa.validateDialogBoxWithSettleVoidCommentDisplayed()
  await pa.selectVoidRadioButton()
  await pa.enterComment('Testing Settle/Void')
  await pa.clickOnSubmit()
  await pa.validateVoidConfirmationMessage()
  await pa.clickOnCancelConfirmationMessagePopUp()
  await pa.clickOnCancelSettleVoidCommentBox()
  await pa.selectComment2()
  await pa.selectSettleVoidButton()
  await pa.selectVoidRadioButton()
  await pa.enterComment('Testing Settle/Void')
  await pa.clickOnSubmit()
  await pa.clickOnConfirm1()
  await pa.validateAuthorizationBox()
  await pa.enterPassword('Password01@$')
  await pa.selectAuthorizationReason('User Error')
  await pa.enterAuthorizationComment('Testing')
  await pa.clickOnAutSubmit()
  await page.waitForTimeout(3000);
  await pa.validateMessageCommentVoidedSuccessfully()
  await pa.clickOnOk_1()
  await pa.clickOnViewSettledVoidedButton()
  await pa.clickOnCloseComment()
  await common.logout();

  });
