import { test, expect } from '@playwright/test';
test.setTimeout(500000);
import { commonSteps } from '../pages/commonSteps';
import { playerAction } from '../pages/playerAction';

test('UH_9456 HALO | Events & Offers | Offer Mgmt/Check-in Flow - Multiple Attendees Single Item Max', async ({ page }) => {
    const common = new commonSteps(page)
    const pa = new playerAction(page)

  await common.goToHALOWebApplication()
  await common.loginAndSubmit("TU_LAB_HALO_NIN_ADM","Password01@$") 
  await pa.clickOnConfiguration()
  await pa.clickOnEventsAndOffers()
  await pa.clickOnManageEventsAndOffers()
  await pa.clickOnAddNewEventAndOffers()
  await pa.ValidateAddNewEventAndOffersPage()
  await pa.SelectfillOutNewEventFields4("Smoke_UH_9456")
  await pa.clickSaveAndNextStep()
  await pa.SelectAFile()
  await pa.clickSaveAndNextStep()
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName1","PC","Skip","500","500")
  await pa.clickOnPrize1()
  await pa.addNewItem("3")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName2","PC","Skip","500","500")
  await pa.clickOnPrize2()
  await pa.addNewItem("3")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName3","PC","Skip","500","500")
  await pa.clickOnPrize3()
  await pa.addNewItem("3")
  await pa.clickSaveAndNextStep()
  await pa.EnterAttendanceCapacity("50")
  await pa.clickSaveAndNextStep()
  await pa.config2()
  await pa.clickSaveAndNextStep()
  await pa.clickSaveAndNextStep()
  await pa.clickSaveAndNextStep()
  await pa.clickOnSubmitForReviewButtonAndVerifyOfferIsSubmittedSuccessfully()
  await pa.validateActiveViewAndApprovedStateSelectedByDefault()
  await pa.selectViewFromEventsAndOfferViewDropdown('All Views')
  await pa.selectStateFromEventsAndOfferStateDropdown('Pending Review')
  await pa.enterOfferName("Smoke_UH_9456")
  await pa.clickOnSearchForEventsAndOffers()
  await pa.selectThreeDotsAfterCreatorColoumn()
  await pa.clickOnView()
  await pa.validateSummaryPageDisplayed()
  await pa.clickOnApprovedOfferTab()
  await pa.validateOfferApprovedSuccessPopUp()
  await pa.clickOnCloseOfferSuccessPopup1()
  await pa.clickOnEmployeeDashboard()
  await pa.clickOnPlayerFunction()
  await pa.playerFunctionsEventCheckin()
  await pa.searchEventInCheckin('Smoke_UH_9456')
  await pa.selectEventInCheckin('Smoke_UH_9456')
  await pa.enterPatronInEventCheckinAndSearch('703039411')
  // await page.waitForTimeout(80000000);
  await pa.clickOnCheckInButtonInEventCheckIn()
  await pa.validateCheckInSuccessfulPopupAndClose()
  await pa.clickPaceReportButton()
  await pa.validatePaceReportPopupIsOpen()
  await pa.closePaceReportPopup()
  await pa.clickOnEmployeeDashboard()
  await pa.enterPlayerID('703039411')
  await pa.clickOnSearchForPlayer()
  await pa.validatePlayerDashboardDisplayed()
  await pa.clickOnCloseComment()
  await pa.clickOnPlayerFunction()
  await pa.clickOnPlayerTransactionLog()
  await pa.clickOnLeftArrow()
  await pa.validateEventDetailsInPlayerTransaction()
  await pa.clickOnclosePlayerTransactionWindow()
  await pa.clickOnPlayerReservation()
  await pa.enterPlayerReservationName('Smoke_UH_9456')
  await pa.clickOnPlayerReservationSearch()
  await pa.clickOnPlayerDetailsLink()
  await pa.validateEventDetailsPageWithSuccessfullCheckin()
  await page.waitForTimeout(4000);
  await common.logout();
  
  });
