import { test, expect } from '@playwright/test';
test.setTimeout(1500000);
import { commonSteps } from '../pages/commonSteps';
import { playerAction } from '../pages/playerAction';

test('UH_9448_HALO | Events & Offers | HALO | Events and Offers | Create offer with Over Ten Items', async ({ page }) => {
    const common = new commonSteps(page)
    const pa = new playerAction(page)

  await common.goToHALOWebApplication()
  await common.loginAndSubmit("TU_LAB_HALO_NIN_ADM","Password01@$") 
  await pa.clickOnConfiguration()
  await pa.clickOnEventsAndOffers()
  await pa.clickOnManageEventsAndOffers()
  await pa.clickOnAddNewEventAndOffers()
  await pa.ValidateAddNewEventAndOffersPage()
  await pa.SelectfillOutNewEventFields4("UH_9448")
  await pa.clickSaveAndNextStep()
  await pa.SelectAFile()
  await pa.clickSaveAndNextStep()
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName1","PC","Skip","500","500")
  await pa.clickOnPrize1()
  await pa.addNewItem("10")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName2","PC","Skip","500","500")
  await pa.clickOnPrize2()
  await pa.addNewItem("10")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName3","PC","Skip","500","500")
  await pa.clickOnPrize3()
  await pa.addNewItem("10")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName4","PC","Skip","500","500")
  await pa.clickOnPrize4()
  await pa.addNewItem("10")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName5","PC","Skip","500","500")
  await pa.clickOnPrize5()
  await pa.addNewItem("10")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName6","PC","Skip","500","500")
  await pa.clickOnPrize6()
  await pa.addNewItem("10")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName7","PC","Skip","500","500")
  await pa.clickOnPrize7()
  await pa.addNewItem("10")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName8","PC","Skip","500","500")
  await pa.clickOnPrize8()
  await pa.addNewItem("10")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName9","PC","Skip","500","500")
  await pa.clickOnPrize9()
  await pa.addNewItem("10")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName10","PC","Skip","500","500")
  await pa.clickOnPrize10()
  await pa.addNewItem("10")
  await pa.clickOnAddMasterListItems()
  await pa.addMasterListItem2("PrizeName11","PC","Skip","500","500") 
  await pa.clickOnPrize11()
  await pa.addNewItem("10")
  await pa.clickSaveAndNextStep()
  await pa.EnterAttendanceCapacity("2")
  await pa.clickSaveAndNextStep()
  await pa.config1()
  await pa.clickSaveAndNextStep()
  await pa.clickSaveAndNextStep()
  await pa.clickSaveAndNextStep()
  await pa.clickOnSubmitForReviewButtonAndVerifyOfferIsSubmittedSuccessfully()
  await pa.validateActiveViewAndApprovedStateSelectedByDefault()
  await pa.selectViewFromEventsAndOfferViewDropdown('Pipeline')
  await pa.selectStateFromEventsAndOfferStateDropdown('Pending Review')
  await pa.enterOfferName('UH_9448')
  await pa.clickOnSearchForEventsAndOffers()
  await pa.selectThreeDotsAfterCreatorColoumn()
  await pa.clickOnView()
  await pa.validateSummaryPageDisplayed()
  await pa.clickOnApprovedOfferTab()
  await pa.validateOfferApprovedSuccessPopUp()
  await pa.clickOnCloseOfferSuccessPopup1()
  await pa.validateActiveViewAndApprovedStateSelectedByDefault()
  await pa.selectViewFromEventsAndOfferViewDropdown('Active')
  await pa.selectStateFromEventsAndOfferStateDropdown('Approved')
  await pa.enterOfferName('UH_9448')
  await pa.clickOnSearchForEventsAndOffers()
  await pa.selectThreeDotsAfterCreatorColoumn()
  await pa.clickOnView()
  await pa.validateSummaryPageDisplayed()
  await common.logout();

   });
