import { test, expect } from '@playwright/test';
test.setTimeout(500000);
import { commonSteps } from '../pages/commonSteps';
import { playerAction } from '../pages/playerAction';

test('UH_9432_HALo | Configuration | Events & Offers | Quick Offers | Create Star Tier Quick Offer', async ({ page }) => {
  const common = new commonSteps(page)
  const pa = new playerAction(page)

  await common.goToHALOWebApplication()
  await common.loginAndSubmit("TU_LAB_HALO_NIN_ADM", "Password01@$")

  await pa.clickOnConfiguration()
  await pa.clickOnEventsAndOffers()
  await pa.clickOnManageQuickOffers()
  await pa.validateQuickOfferSetupPageWithActiveQuickOffersDisplayed()
  await pa.clickOnAddNewQuickOffer()
  await pa.validateNewQuickOfferSetupPageDisplayed()
  await pa.validateInLobCasinoOptionSelectedByDefault()
  await pa.clickOnOfferTypeDropdownWhenCasinoIsSelectedInQuickOfferPage()
  await pa.selectOfferTypeQuickOfferPage()
  await pa.clickOnDisplayPropertyDropdownQuickOfferSetupPage()
  await pa.checkOptionDisplayPropertyQuickOffer('Hard Rock Atlantic City')
  await pa.clickOnDisplayLocationDropdown()
  await pa.checkOptionOfDisplayLocationQuickOfferSetupPage('Players Club')
  await pa.enterDisplayName('UH_9432_Smoke')
  await pa.clickOnCardTierRestrictionDropdownQuickOfferSetupPage()
  await pa.selecCardTierRestrictionStarQuickOfferPage()
  await pa.enterDisplayDescriptionInQuickOfferPage('Test')
  await pa.enterDisclaimerInQuickOfferPage('Test1')
  await pa.clickOnSaveAndNextStepQuickOfferPage()
  await pa.validateSelectAFileButtonDisplayedInInviteeListSection()
  await pa.validateUploadButtonDisplayedInInviteeListSection()
  await pa.clickOnSaveAndNextInvitationDetailsPage()
  await pa.clickOnSubmitButton()
  await pa.validateOfferSuccessfullySubmittedMessage()
  await pa.clickOnCloseSuccessPopUp()
  await pa.enterOfferNameInSearchBox('UH_9432_Smoke')
  await pa.clickOnSearchForQuickOffer()
  //await page.waitForTimeout(8000000);
  await pa.validateOfferCreated2Displayed()
  await pa.clickOnExpandPlayerSearchIcon()
  await pa.enterPlayerID('807651715')
  await pa.clickOnSearchForPlayer()
  await pa.clickOnViewEventsAndOffers()
  await pa.enterEventOfferNameInSearchBox('UH_9432_Smoke')
  await pa.clickOnSearchViewEventAndOffer()
  await pa.validateCreatedOfferInEventAndOffersTabForStarCardDisplayed()
  await pa.clickOnExpandPlayerSearchIcon()
  await pa.enterPlayerID('807879852')
  await pa.clickOnSearchForPlayer()
  await pa.clickOnViewEventsAndOffers()
  await pa.enterEventOfferNameInSearchBox('UH_9432_Smoke')
  await pa.clickOnSearchViewEventAndOffer()
  // await pa.validateOfferCreatedNotDisplayed()
  //await page.waitForTimeout(8000000);
  //await pa.validateOfferInEventsAndOfferCreatedDisplayed()
  await pa.clickOnExpandPlayerSearchIcon()
  await pa.enterPlayerID('703039411')
  await pa.clickOnSearchForPlayer()
  await pa.clickOnClose()
  await pa.clickOnViewEventsAndOffers()
  await pa.enterEventOfferNameInSearchBox('UH_9432_Smoke')
  await pa.clickOnSearchViewEventAndOffer()
  // await pa.validateOfferCreatedNotDisplayed()
  //await pa.validateOfferInEventsAndOfferCreatedDisplayed()
  await pa.clickOnExpandPlayerSearchIcon()
  await pa.enterPlayerID('660302931')
  await pa.clickOnSearchForPlayer()
  await pa.clickOnClose()
  await pa.clickOnViewEventsAndOffers()
  await pa.enterEventOfferNameInSearchBox('UH_9432_Smoke')
  await pa.clickOnSearchViewEventAndOffer()
  await common.logout();

});
