#==========================================================================#
# This is file has all the configuration settings for running a test suite #
#==========================================================================#

# This below parameter decides in which browser to run the test suite #
# List of Browser are as follows: CHROME,FIREFOX,IE,CHROME_HEADLESS,FIREFOX_HEADLESS,HTML_UNIT_DRIVER ,PHANTOM_JS
#browser: FIREFOX
#browser: CHROME
browser: EDGE
#browser: PHANTOM_JS
#browser: MSEDGEDRIVER
#browser: CHROME_HEADLESS

# This below parameter decides Environment URL #
#Halo Admin
url: https://haqasga-wbapp-1.seminolehardrock.fl.local/HaloWebApp/Login.aspx
#Prod URL - DO not use if not knowing how to run Prod Script
#url: https://sg24-hawbapp-1.seminolehardrock.fl.local/HaloWebApp/Login.aspx
# This below parameter decides the wait Time in seconds #

webdriverWaitTime: 25

# Admin SignIn Credentials use by script
email: 'TU_LAB_HALO_NIN_ADM'
password: 'Password01@$'

#User SignIn Credentials not use by script
#userEmail: 'TU_LAB_HALO_GenUSR'
#userPassword: 'Password01@$'


#PROD SignIn Credentials
#email: 'milou.rene'
#password: 'XXXXXXX'


comments: 'The reason is updating in the work notes as field Changes'
replycomments: 'Is it possible to update as additional comments'
editcomments: 'Word shows your comment in the document margin'
addcomments: 'Select the text you want to comment'

homephonenumber: '1111111111'
mobilephonenumber: '8888888888'
emailaddress: 'qaAutomationTeam@shrss.com'
addhomephonenumber: '1111111111'
addmobilephonenumber: '8888888888'
#addmobilephonenumber: '6198663842'
newemailaddress: 'qaAutomationTeam@shrss.com'
#newemailaddress: 'steveronese@gmail.com'

homeaddressone: '9544 Seminole drive'
homeaddresstwo: 'QA Automation'
homecity: 'Hollywood'
homezipcode: '92103'
homeaddressfromdate: '06/12/21'
homeaddresstodate: '06/11/22'

alternateaddressone: '163 Dessaline Road'
alternateaddresstwo: '52 Kalalou'
alternatecity: 'Aquin'
alternatezipcode: '10036'
alternateaddressfromdate: '08/12/21'
alternateaddresstodate: '08/11/22'

preferredfromdate: '04102023'
preferredtodate: '04232023'
searchtransaction: 'Address Preference - Update Home'

EventsFromdate: '04222023'
eventsToDate: '04123023'

searchoutlet: 'HGNIN-Constant Grind'

xray.jira.apikey.header: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnQiOiIzZGY5MGVjYi02N2MxLTM0MDktOTc0NC1jZjliMDExMjIxN2IiLCJhY2NvdW50SWQiOiI2NDAyMGEzMDBhNGE0N2ZiOGQyMjQ2YjgiLCJpc1hlYSI6ZmFsc2UsImlhdCI6MTcwNzkzODU0MSwiZXhwIjoxNzA4MDI0OTQxLCJhdWQiOiI5MUI4Qjg2MERFRjc0NzUwODcwMjRGMzYxMDZDRTFEMCIsImlzcyI6ImNvbS54cGFuZGl0LnBsdWdpbnMueHJheSIsInN1YiI6IjkxQjhCODYwREVGNzQ3NTA4NzAyNEYzNjEwNkNFMUQwIn0.eCuxuWltQLbMeqqTGiBtJGWFFNRgycC7h7pvvc8QM90'
xray.test.execution.key: 'UH-23031'